--------------------------------------------------------
--  DDL for Table I_STORE_INFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_STORE_INFO" 
   (	"STORE_ID" VARCHAR2(15 BYTE), 
	"STORE_NAME" VARCHAR2(100 BYTE), 
	"STORE_TYPE" VARCHAR2(50 BYTE), 
	"LOCATION" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" NUMBER(15,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"YEAR_FOUNDED" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_USERS" 
   (	"USER_ID" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"PHONE_NUMBER" NUMBER(15,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"STORE_ID" VARCHAR2(15 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_RECEIPT_ITEM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_RECEIPT_ITEM" 
   (	"RECEIPT_ITEM_ID" VARCHAR2(15 BYTE), 
	"QUANTITY" NUMBER, 
	"TOTAL_PER_ITEM" NUMBER(10,2), 
	"RECEIPT_ID" VARCHAR2(15 BYTE), 
	"ITEM_ID" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_RECEIPT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_RECEIPT" 
   (	"RECEIPT_ID" VARCHAR2(15 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"TOTAL_PRICE" NUMBER(10,2), 
	"USER_ID" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_INVENTORY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_INVENTORY" 
   (	"ITEM_ID" VARCHAR2(15 BYTE), 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"QUANTITY" NUMBER DEFAULT 0, 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"HARGA_BELI" NUMBER(10,2), 
	"HARGA_JUAL" NUMBER(10,2), 
	"STATUS" VARCHAR2(50 BYTE), 
	"DATE_EXPIRED" DATE, 
	"USER_ID" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_DAMAGED_ITEM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_DAMAGED_ITEM" 
   (	"DAMAGED_ID" VARCHAR2(15 BYTE), 
	"DATE_DAMAGED" DATE DEFAULT SYSDATE, 
	"DAMAGED_DESC" VARCHAR2(255 BYTE), 
	"QTY_DAMAGED" NUMBER, 
	"ACTION" VARCHAR2(100 BYTE), 
	"COST" NUMBER(10,2), 
	"ITEM_ID" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009365
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009365" ON "SYSTEM"."I_STORE_INFO" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009366
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009366" ON "SYSTEM"."I_STORE_INFO" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009367
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009367" ON "SYSTEM"."I_STORE_INFO" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009370
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009370" ON "SYSTEM"."I_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009371
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009371" ON "SYSTEM"."I_USERS" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009372
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009372" ON "SYSTEM"."I_USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009381
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009381" ON "SYSTEM"."I_RECEIPT_ITEM" ("RECEIPT_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009377
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009377" ON "SYSTEM"."I_RECEIPT" ("RECEIPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009375
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009375" ON "SYSTEM"."I_INVENTORY" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009384
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009384" ON "SYSTEM"."I_DAMAGED_ITEM" ("DAMAGED_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_STORE_INFO_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_STORE_INFO_ID" 
BEFORE INSERT ON I_STORE_INFO
FOR EACH ROW
BEGIN
    :NEW.STORE_ID := 'STR' || STORE_INFO_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_STORE_INFO_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_USERS_ID" 
BEFORE INSERT ON I_USERS
FOR EACH ROW
BEGIN
    :NEW.USER_ID := 'USR' || USERS_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_store_info_id
BEFORE INSERT ON I_STORE_INFO
FOR EACH ROW
BEGIN
    :NEW.STORE_ID := 'STR' || STORE_INFO_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_inventory_id
BEFORE INSERT ON I_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.ITEM_ID := 'ITM' || INVENTORY_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_receipt_id
BEFORE INSERT ON I_RECEIPT
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ID := 'RCP' || RECEIPT_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_receipt_item_id
BEFORE INSERT ON I_RECEIPT_ITEM
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ITEM_ID := 'RIT' || RECEIPT_ITEM_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_damaged_item_id
BEFORE INSERT ON I_DAMAGED_ITEM
FOR EACH ROW
BEGIN
    :NEW.DAMAGED_ID := 'DMG' || DAMAGED_ITEM_SEQ.NEXTVAL;
END;


select * from i_store_info;
/
ALTER TRIGGER "SYSTEM"."TRG_USERS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_RECEIPT_ITEM_ID" 
BEFORE INSERT ON I_RECEIPT_ITEM
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ITEM_ID := 'RIT' || RECEIPT_ITEM_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_RECEIPT_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_RECEIPT_ID" 
BEFORE INSERT ON I_RECEIPT
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ID := 'RCP' || RECEIPT_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_RECEIPT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INVENTORY_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_INVENTORY_ID" 
BEFORE INSERT ON I_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.ITEM_ID := 'ITM' || INVENTORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_INVENTORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DAMAGED_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_DAMAGED_ITEM_ID" 
BEFORE INSERT ON I_DAMAGED_ITEM
FOR EACH ROW
BEGIN
    :NEW.DAMAGED_ID := 'DMG' || DAMAGED_ITEM_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_DAMAGED_ITEM_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table I_STORE_INFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_STORE_INFO" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_STORE_INFO" ADD PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."I_STORE_INFO" ADD UNIQUE ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."I_STORE_INFO" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."I_USERS" ADD UNIQUE ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."I_USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_RECEIPT_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" MODIFY ("TOTAL_PER_ITEM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" ADD PRIMARY KEY ("RECEIPT_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_RECEIPT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_RECEIPT" ADD PRIMARY KEY ("RECEIPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_INVENTORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_INVENTORY" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_INVENTORY" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_DAMAGED_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_DAMAGED_ITEM" ADD PRIMARY KEY ("DAMAGED_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_USERS" ADD FOREIGN KEY ("STORE_ID")
	  REFERENCES "SYSTEM"."I_STORE_INFO" ("STORE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_RECEIPT_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" ADD FOREIGN KEY ("RECEIPT_ID")
	  REFERENCES "SYSTEM"."I_RECEIPT" ("RECEIPT_ID") ENABLE;
  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" ADD FOREIGN KEY ("ITEM_ID")
	  REFERENCES "SYSTEM"."I_INVENTORY" ("ITEM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_RECEIPT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_RECEIPT" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."I_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_INVENTORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_INVENTORY" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."I_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_DAMAGED_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_DAMAGED_ITEM" ADD FOREIGN KEY ("ITEM_ID")
	  REFERENCES "SYSTEM"."I_INVENTORY" ("ITEM_ID") ENABLE;
