--------------------------------------------------------
--  File created - Tuesday-December-24-2024   
--------------------------------------------------------
DROP SEQUENCE "C##INVENSYNC"."INVENTORY_SEQ";
DROP SEQUENCE "C##INVENSYNC"."MASTER_BRAND_SEQ";
DROP SEQUENCE "C##INVENSYNC"."MASTER_CATEGORY_SEQ";
DROP SEQUENCE "C##INVENSYNC"."MASTER_ITEM_SEQ";
DROP SEQUENCE "C##INVENSYNC"."RECEIPT_ITEM_SEQ";
DROP SEQUENCE "C##INVENSYNC"."RECEIPT_SEQ";
DROP SEQUENCE "C##INVENSYNC"."STORE_INFO_SEQ";
DROP SEQUENCE "C##INVENSYNC"."USERS_SEQ";
DROP TABLE "C##INVENSYNC"."I_STORE_INFO" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_RECEIPT" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_MASTER_ITEM" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_USERS" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_MASTER_BRAND" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_INVENTORY" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" cascade constraints;
DROP PROCEDURE "C##INVENSYNC"."ADD_CATEGORY";
DROP FUNCTION "C##INVENSYNC"."ANNUALREVENUE";
--------------------------------------------------------
--  DDL for Sequence INVENTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."INVENTORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 148 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MASTER_BRAND_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."MASTER_BRAND_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 111 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MASTER_CATEGORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."MASTER_CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 112 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MASTER_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."MASTER_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 113 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RECEIPT_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."RECEIPT_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 135 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RECEIPT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."RECEIPT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 123 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STORE_INFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."STORE_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 125 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 133 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table I_STORE_INFO
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_STORE_INFO" 
   (	"STORE_NAME" VARCHAR2(100 BYTE), 
	"STORE_TYPE" VARCHAR2(50 BYTE), 
	"LOCATION" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" NUMBER(15,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"YEAR_FOUNDED" NUMBER, 
	"STORE_ID" VARCHAR2(255 BYTE), 
	"OWNER_ID" VARCHAR2(255 BYTE), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_MASTER_CATEGORY
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" 
   (	"CATEGORY_ID" VARCHAR2(50 BYTE), 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"IS_DELETED" NUMBER DEFAULT 0, 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_RECEIPT
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_RECEIPT" 
   (	"RECEIPT_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"TOTAL_PRICE" NUMBER(10,2), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"TIME_ADDED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_MASTER_ITEM
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_MASTER_ITEM" 
   (	"ITEM_ID" VARCHAR2(50 BYTE), 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"COST_PRICE" NUMBER, 
	"CATEGORY_ID" VARCHAR2(50 BYTE), 
	"IS_DELETED" NUMBER DEFAULT 0, 
	"BRAND_ID" VARCHAR2(50 BYTE), 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_USERS
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_USERS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"PHONE_NUMBER" NUMBER(15,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"OWNER_ID" VARCHAR2(255 BYTE), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0, 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"IS_EMAIL_VERIFIED" NUMBER(1,0) DEFAULT 0, 
	"VERIFICATION_TOKEN" VARCHAR2(255 BYTE), 
	"CODE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_MASTER_BRAND
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_MASTER_BRAND" 
   (	"BRAND_ID" VARCHAR2(50 BYTE), 
	"BRAND_NAME" VARCHAR2(100 BYTE), 
	"IS_DELETED" NUMBER DEFAULT 0, 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_INVENTORY
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_INVENTORY" 
   (	"ITEM_ID" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER DEFAULT 0, 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"HARGA_BELI" NUMBER(10,2), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0, 
	"INVENTORY_ID" VARCHAR2(50 BYTE), 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE) DEFAULT 'Pending'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_RECEIPT_ITEM
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" 
   (	"RECEIPT_ITEM_ID" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER, 
	"TOTAL_PER_ITEM" NUMBER(10,2), 
	"RECEIPT_ID" VARCHAR2(50 BYTE), 
	"ITEM_ID" VARCHAR2(50 BYTE), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0, 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"TIME_ADDED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009426
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009426" ON "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009491
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009491" ON "C##INVENSYNC"."I_MASTER_CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009418
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009418" ON "C##INVENSYNC"."I_RECEIPT" ("RECEIPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009438
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009438" ON "C##INVENSYNC"."I_MASTER_ITEM" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009411
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009411" ON "C##INVENSYNC"."I_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009489
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009489" ON "C##INVENSYNC"."I_MASTER_BRAND" ("BRAND_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INVENTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."PK_INVENTORY" ON "C##INVENSYNC"."I_INVENTORY" ("INVENTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009422
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009422" ON "C##INVENSYNC"."I_RECEIPT_ITEM" ("RECEIPT_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_USERS_ID" 
BEFORE INSERT ON I_USERS
FOR EACH ROW
BEGIN
    :NEW.USER_ID := 'UID' || USERS_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_USERS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_CATEGORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_CATEGORY_ID" 
BEFORE INSERT ON I_MASTER_CATEGORY
FOR EACH ROW
BEGIN
    :NEW.CATEGORY_ID := 'CTG' || MASTER_CATEGORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_CATEGORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INVENTORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_INVENTORY_ID" 
BEFORE INSERT ON I_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.INVENTORY_ID := 'INV' || INVENTORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_INVENTORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_ITEM_ID" 
BEFORE INSERT ON I_MASTER_ITEM
FOR EACH ROW
BEGIN
    :NEW.ITEM_ID := 'ITM' || MASTER_ITEM_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ID" 
BEFORE INSERT ON I_RECEIPT
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ID := 'RCP' || RECEIPT_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STORE_INFO_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_STORE_INFO_ID" 
BEFORE INSERT ON I_STORE_INFO
FOR EACH ROW
BEGIN
    :NEW.STORE_ID := 'STR' || STORE_INFO_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_STORE_INFO_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ITEM_ID" 
BEFORE INSERT ON I_RECEIPT_ITEM
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ITEM_ID := 'RIT' || RECEIPT_ITEM_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_BRAND_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_BRAND_ID" 
BEFORE INSERT ON I_MASTER_BRAND
FOR EACH ROW
BEGIN
    :NEW.BRAND_ID := 'BRN' || MASTER_BRAND_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_BRAND_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STORE_INFO_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_STORE_INFO_ID" 
BEFORE INSERT ON I_STORE_INFO
FOR EACH ROW
BEGIN
    :NEW.STORE_ID := 'STR' || STORE_INFO_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_STORE_INFO_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_CATEGORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_CATEGORY_ID" 
BEFORE INSERT ON I_MASTER_CATEGORY
FOR EACH ROW
BEGIN
    :NEW.CATEGORY_ID := 'CTG' || MASTER_CATEGORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_CATEGORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ID" 
BEFORE INSERT ON I_RECEIPT
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ID := 'RCP' || RECEIPT_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_ITEM_ID" 
BEFORE INSERT ON I_MASTER_ITEM
FOR EACH ROW
BEGIN
    :NEW.ITEM_ID := 'ITM' || MASTER_ITEM_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_USERS_ID" 
BEFORE INSERT ON I_USERS
FOR EACH ROW
BEGIN
    :NEW.USER_ID := 'UID' || USERS_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_USERS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_BRAND_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_BRAND_ID" 
BEFORE INSERT ON I_MASTER_BRAND
FOR EACH ROW
BEGIN
    :NEW.BRAND_ID := 'BRN' || MASTER_BRAND_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_BRAND_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INVENTORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_INVENTORY_ID" 
BEFORE INSERT ON I_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.INVENTORY_ID := 'INV' || INVENTORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_INVENTORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ITEM_ID" 
BEFORE INSERT ON I_RECEIPT_ITEM
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ITEM_ID := 'RIT' || RECEIPT_ITEM_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADD_CATEGORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "C##INVENSYNC"."ADD_CATEGORY" (
    p_category_name IN VARCHAR2, -- Parameter input
    p_store_id IN VARCHAR2         -- Parameter input
) AS
BEGIN
    INSERT INTO i_master_category (category_name, store_id)
    VALUES (p_category_name, p_store_id);
END;

/
--------------------------------------------------------
--  DDL for Function ANNUALREVENUE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "C##INVENSYNC"."ANNUALREVENUE" (
    p_store_id IN VARCHAR2,
    p_tahun IN VARCHAR2
) RETURN VARCHAR2 IS
    v_total_pengeluaran NUMBER := 0;
    v_total_pendapatan NUMBER := 0;
    v_profit NUMBER := 0;
BEGIN
    -- Menghitung Total Pengeluaran
    SELECT NVL(SUM(i.QUANTITY * i.HARGA_BELI), 0)
    INTO v_total_pengeluaran
    FROM I_INVENTORY i
    WHERE i.IS_DELETED = 0 
      AND i.STORE_ID = p_store_id
      AND TO_CHAR(i.date_added, 'YYYY') = p_tahun;

    -- Menghitung Total Pendapatan
    SELECT NVL(SUM(r.QUANTITY * m.COST_PRICE), 0)
    INTO v_total_pendapatan
    FROM I_RECEIPT_ITEM r
    JOIN I_MASTER_ITEM m ON r.ITEM_ID = m.ITEM_ID
    WHERE r.IS_DELETED = 0 
      AND m.IS_DELETED = 0
      AND r.STORE_ID = p_store_id
      AND m.STORE_ID = p_store_id
      AND TO_CHAR(r.time_added, 'YYYY') = p_tahun;

    -- Menghitung Profit
    v_profit := v_total_pendapatan - v_total_pengeluaran;

    -- Mengembalikan hasil sebagai string
    RETURN v_total_pengeluaran || ',' || v_total_pendapatan || ',' || v_profit;
END;

/
--------------------------------------------------------
--  Constraints for Table I_STORE_INFO
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_STORE_INFO" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_STORE_INFO" ADD PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_MASTER_CATEGORY
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_RECEIPT
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_RECEIPT" ADD PRIMARY KEY ("RECEIPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_MASTER_ITEM
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" MODIFY ("COST_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_USERS
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_USERS" MODIFY ("IS_DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table I_MASTER_BRAND
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_BRAND" MODIFY ("BRAND_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_MASTER_BRAND" ADD PRIMARY KEY ("BRAND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_INVENTORY
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" ADD CONSTRAINT "PK_INVENTORY" PRIMARY KEY ("INVENTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_RECEIPT_ITEM
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" MODIFY ("TOTAL_PER_ITEM" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" ADD PRIMARY KEY ("RECEIPT_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" MODIFY ("IS_DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table I_STORE_INFO
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_STORE_INFO" ADD CONSTRAINT "FK_OWNERSTORE" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "C##INVENSYNC"."I_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_MASTER_CATEGORY
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" ADD CONSTRAINT "FK_STORE_CATEGORY" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_RECEIPT
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_RECEIPT" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "C##INVENSYNC"."I_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT" ADD CONSTRAINT "FK_STORE_RECEIPT" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_MASTER_ITEM
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" ADD CONSTRAINT "FK_BRAND_ITEM" FOREIGN KEY ("BRAND_ID")
	  REFERENCES "C##INVENSYNC"."I_MASTER_BRAND" ("BRAND_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" ADD CONSTRAINT "FK_CATEGORY_ITEM" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "C##INVENSYNC"."I_MASTER_CATEGORY" ("CATEGORY_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" ADD CONSTRAINT "FK_STORE_ITEM" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_USERS
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_USERS" ADD CONSTRAINT "FK_OWNERID" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "C##INVENSYNC"."I_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_USERS" ADD CONSTRAINT "FK_STORE_USERS" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_MASTER_BRAND
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_BRAND" ADD CONSTRAINT "FK_STORE_BRAND" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_INVENTORY
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "C##INVENSYNC"."I_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" ADD CONSTRAINT "FK_INVENTORY_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "C##INVENSYNC"."I_MASTER_ITEM" ("ITEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" ADD CONSTRAINT "FK_STORE_INVENTORY" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_RECEIPT_ITEM
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" ADD FOREIGN KEY ("RECEIPT_ID")
	  REFERENCES "C##INVENSYNC"."I_RECEIPT" ("RECEIPT_ID") ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" ADD CONSTRAINT "FK_RECEIPT_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "C##INVENSYNC"."I_MASTER_ITEM" ("ITEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" ADD CONSTRAINT "FK_RECEIPT_ITEM_USERS" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
