--------------------------------------------------------
--  File created - Tuesday-December-17-2024   
--------------------------------------------------------
DROP SEQUENCE "C##INVENSYNC"."MASTER_BRAND_SEQ";
DROP SEQUENCE "C##INVENSYNC"."MASTER_CATEGORY_SEQ";
DROP SEQUENCE "C##INVENSYNC"."INVENTORY_SEQ";
DROP SEQUENCE "C##INVENSYNC"."MASTER_ITEM_SEQ";
DROP SEQUENCE "C##INVENSYNC"."RECEIPT_ITEM_SEQ";
DROP SEQUENCE "C##INVENSYNC"."RECEIPT_SEQ";
DROP SEQUENCE "C##INVENSYNC"."STORE_INFO_SEQ";
DROP SEQUENCE "C##INVENSYNC"."USERS_SEQ";
DROP TABLE "C##INVENSYNC"."I_INVENTORY" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_RECEIPT" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_MASTER_BRAND" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_STORE_INFO" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_USERS" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" cascade constraints;
DROP TABLE "C##INVENSYNC"."I_MASTER_ITEM" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence MASTER_BRAND_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."MASTER_BRAND_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 109 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MASTER_CATEGORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."MASTER_CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 107 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INVENTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."INVENTORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 127 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MASTER_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."MASTER_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 107 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RECEIPT_ITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."RECEIPT_ITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence RECEIPT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."RECEIPT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 112 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STORE_INFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."STORE_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 124 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##INVENSYNC"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 131 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table I_INVENTORY
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_INVENTORY" 
   (	"ITEM_ID" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER DEFAULT 0, 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"HARGA_BELI" NUMBER(10,2), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0, 
	"INVENTORY_ID" VARCHAR2(50 BYTE), 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE) DEFAULT 'Pending'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_RECEIPT
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_RECEIPT" 
   (	"RECEIPT_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"TOTAL_PRICE" NUMBER(10,2), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"TIME_ADDED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_MASTER_BRAND
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_MASTER_BRAND" 
   (	"BRAND_ID" VARCHAR2(50 BYTE), 
	"BRAND_NAME" VARCHAR2(100 BYTE), 
	"IS_DELETED" NUMBER DEFAULT 0, 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_MASTER_CATEGORY
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" 
   (	"CATEGORY_ID" VARCHAR2(50 BYTE), 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"IS_DELETED" NUMBER DEFAULT 0, 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_STORE_INFO
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_STORE_INFO" 
   (	"STORE_NAME" VARCHAR2(100 BYTE), 
	"STORE_TYPE" VARCHAR2(50 BYTE), 
	"LOCATION" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" NUMBER(15,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"YEAR_FOUNDED" NUMBER, 
	"STORE_ID" VARCHAR2(255 BYTE), 
	"OWNER_ID" VARCHAR2(255 BYTE), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_USERS
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_USERS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"PHONE_NUMBER" NUMBER(15,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"OWNER_ID" VARCHAR2(255 BYTE), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0, 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"IS_EMAIL_VERIFIED" NUMBER(1,0) DEFAULT 0, 
	"VERIFICATION_TOKEN" VARCHAR2(255 BYTE), 
	"CODE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_RECEIPT_ITEM
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" 
   (	"RECEIPT_ITEM_ID" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER, 
	"TOTAL_PER_ITEM" NUMBER(10,2), 
	"RECEIPT_ID" VARCHAR2(50 BYTE), 
	"ITEM_ID" VARCHAR2(50 BYTE), 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0, 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"TIME_ADDED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table I_MASTER_ITEM
--------------------------------------------------------

  CREATE TABLE "C##INVENSYNC"."I_MASTER_ITEM" 
   (	"ITEM_ID" VARCHAR2(50 BYTE), 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"COST_PRICE" NUMBER, 
	"CATEGORY_ID" VARCHAR2(50 BYTE), 
	"IS_DELETED" NUMBER DEFAULT 0, 
	"BRAND_ID" VARCHAR2(50 BYTE), 
	"STORE_ID" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##INVENSYNC.I_INVENTORY
SET DEFINE OFF;
Insert into C##INVENSYNC.I_INVENTORY (ITEM_ID,QUANTITY,DATE_ADDED,HARGA_BELI,USER_ID,IS_DELETED,INVENTORY_ID,STORE_ID,STATUS) values ('ITM102','11',to_date('06-12-2024','DD-MM-RRRR'),'161000','UID119','0','INV120','STR112','Pending');
Insert into C##INVENSYNC.I_INVENTORY (ITEM_ID,QUANTITY,DATE_ADDED,HARGA_BELI,USER_ID,IS_DELETED,INVENTORY_ID,STORE_ID,STATUS) values ('ITM106','15',to_date('11-12-2024','DD-MM-RRRR'),'219000','UID119','0','INV124','STR112','Pending');
Insert into C##INVENSYNC.I_INVENTORY (ITEM_ID,QUANTITY,DATE_ADDED,HARGA_BELI,USER_ID,IS_DELETED,INVENTORY_ID,STORE_ID,STATUS) values ('ITM102','30',to_date('06-12-2024','DD-MM-RRRR'),'157900','UID119','0','INV119','STR112','Pending');
Insert into C##INVENSYNC.I_INVENTORY (ITEM_ID,QUANTITY,DATE_ADDED,HARGA_BELI,USER_ID,IS_DELETED,INVENTORY_ID,STORE_ID,STATUS) values ('ITM104','90',to_date('06-12-2024','DD-MM-RRRR'),'134500','UID119','0','INV121','STR112','Pending');
Insert into C##INVENSYNC.I_INVENTORY (ITEM_ID,QUANTITY,DATE_ADDED,HARGA_BELI,USER_ID,IS_DELETED,INVENTORY_ID,STORE_ID,STATUS) values ('ITM105','12',to_date('10-12-2024','DD-MM-RRRR'),'223400','UID121','0','INV122','STR119','Pending');
Insert into C##INVENSYNC.I_INVENTORY (ITEM_ID,QUANTITY,DATE_ADDED,HARGA_BELI,USER_ID,IS_DELETED,INVENTORY_ID,STORE_ID,STATUS) values ('ITM101','50',to_date('10-12-2024','DD-MM-RRRR'),'91300','UID119','0','INV123','STR112','Pending');
Insert into C##INVENSYNC.I_INVENTORY (ITEM_ID,QUANTITY,DATE_ADDED,HARGA_BELI,USER_ID,IS_DELETED,INVENTORY_ID,STORE_ID,STATUS) values ('ITM106','14',to_date('14-11-2024','DD-MM-RRRR'),'219000','UID119','0','INV125','STR112','Pending');
REM INSERTING into C##INVENSYNC.I_RECEIPT
SET DEFINE OFF;
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP109',to_date('14-11-2024','DD-MM-RRRR'),null,'UID119','STR112',to_timestamp('14-11-2024 19.41.41,092000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP111',to_date('17-12-2024','DD-MM-RRRR'),null,'UID119','STR112',to_timestamp('17-12-2024 16.22.34,005000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP101',to_date('08-12-2024','DD-MM-RRRR'),null,'UID119','STR112',to_timestamp('08-12-2024 01.26.08,355000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP107',to_date('14-12-2024','DD-MM-RRRR'),'430000','UID119','STR112',to_timestamp('14-12-2024 15.58.12,366000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP102',to_date('10-12-2024','DD-MM-RRRR'),null,'UID119','STR112',to_timestamp('10-12-2024 23.24.42,019000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP103',to_date('11-12-2024','DD-MM-RRRR'),null,'UID119','STR112',to_timestamp('11-12-2024 12.30.17,796000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP104',to_date('11-12-2024','DD-MM-RRRR'),null,'UID119','STR112',to_timestamp('11-12-2024 12.31.05,146000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP105',to_date('11-12-2024','DD-MM-RRRR'),null,'UID119','STR112',to_timestamp('11-12-2024 13.52.48,022000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP106',to_date('12-12-2024','DD-MM-RRRR'),null,'UID119','STR112',to_timestamp('12-12-2024 12.09.58,738000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP108',to_date('14-12-2024','DD-MM-RRRR'),'2141400','UID119','STR112',to_timestamp('14-12-2024 15.59.05,094000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
Insert into C##INVENSYNC.I_RECEIPT (RECEIPT_ID,DATE_ADDED,TOTAL_PRICE,USER_ID,STORE_ID,TIME_ADDED,IS_DELETED) values ('RCP110',to_date('17-12-2024','DD-MM-RRRR'),'-192000','UID119','STR112',to_timestamp('17-12-2024 13.28.05,599000000','DD-MM-RRRR HH24.MI.SSXFF'),'0');
REM INSERTING into C##INVENSYNC.I_MASTER_BRAND
SET DEFINE OFF;
Insert into C##INVENSYNC.I_MASTER_BRAND (BRAND_ID,BRAND_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('BRN101','Magma','0','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_BRAND (BRAND_ID,BRAND_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('BRN102','Uniqlo','0','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_BRAND (BRAND_ID,BRAND_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('BRN105','Ooptimum','0','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_BRAND (BRAND_ID,BRAND_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('BRN107','Eiger','0','STR119',to_date('10-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_BRAND (BRAND_ID,BRAND_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('BRN108','Eiger','0','STR112',to_date('11-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_BRAND (BRAND_ID,BRAND_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('BRN103','Miniso','0','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_BRAND (BRAND_ID,BRAND_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('BRN104','Celcius','0','STR120',to_date('06-12-2024','DD-MM-RRRR'));
REM INSERTING into C##INVENSYNC.I_MASTER_CATEGORY
SET DEFINE OFF;
Insert into C##INVENSYNC.I_MASTER_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('CTG101','Topi','0','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('CTG104','Kemeja','0','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('CTG106','Tas','0','STR112',to_date('11-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('CTG103','Kemeja','0','STR120',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('CTG105','Tas','0','STR119',to_date('10-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_CATEGORY (CATEGORY_ID,CATEGORY_NAME,IS_DELETED,STORE_ID,DATE_ADDED) values ('CTG102','Celana','0','STR112',to_date('06-12-2024','DD-MM-RRRR'));
REM INSERTING into C##INVENSYNC.I_STORE_INFO
SET DEFINE OFF;
Insert into C##INVENSYNC.I_STORE_INFO (STORE_NAME,STORE_TYPE,LOCATION,PHONE_NUMBER,EMAIL,DATE_CREATED,YEAR_FOUNDED,STORE_ID,OWNER_ID,IS_DELETED) values ('Toko Ikhlas','Toko Sepatu','Jakarta Utara','8917231642','tokoikhlas@gmail.com',to_date('05-12-2024','DD-MM-RRRR'),'2004','STR119','UID121','0');
Insert into C##INVENSYNC.I_STORE_INFO (STORE_NAME,STORE_TYPE,LOCATION,PHONE_NUMBER,EMAIL,DATE_CREATED,YEAR_FOUNDED,STORE_ID,OWNER_ID,IS_DELETED) values ('Toko Gecof','Toko Sepatu','Pasar Baru','84783982328','gecof.pnj@gmail.com',to_date('10-12-2024','DD-MM-RRRR'),'2024','STR122','UID128','0');
Insert into C##INVENSYNC.I_STORE_INFO (STORE_NAME,STORE_TYPE,LOCATION,PHONE_NUMBER,EMAIL,DATE_CREATED,YEAR_FOUNDED,STORE_ID,OWNER_ID,IS_DELETED) values ('Bankzhat','Toko Distro','Lenteng Agung','8123456789','bankzhat@gmail.com',to_date('06-12-2024','DD-MM-RRRR'),'2020','STR120','UID123','0');
Insert into C##INVENSYNC.I_STORE_INFO (STORE_NAME,STORE_TYPE,LOCATION,PHONE_NUMBER,EMAIL,DATE_CREATED,YEAR_FOUNDED,STORE_ID,OWNER_ID,IS_DELETED) values ('Bankzhat','Toko Distro','Lenteng Agung','8123456789','bankzhat@gmail.com',to_date('06-12-2024','DD-MM-RRRR'),'2020','STR121','UID123','0');
Insert into C##INVENSYNC.I_STORE_INFO (STORE_NAME,STORE_TYPE,LOCATION,PHONE_NUMBER,EMAIL,DATE_CREATED,YEAR_FOUNDED,STORE_ID,OWNER_ID,IS_DELETED) values ('Zam Store','Toko Distro','Pasar Minggu','81234567891','zam@gmail.com',to_date('27-11-2024','DD-MM-RRRR'),'2019','STR112','UID119','0');
Insert into C##INVENSYNC.I_STORE_INFO (STORE_NAME,STORE_TYPE,LOCATION,PHONE_NUMBER,EMAIL,DATE_CREATED,YEAR_FOUNDED,STORE_ID,OWNER_ID,IS_DELETED) values ('Zam','Toko Distro','Pasar Minggu','8123456784','zamstore@gmail.com',to_date('15-12-2024','DD-MM-RRRR'),'2024','STR123','UID129','0');
REM INSERTING into C##INVENSYNC.I_USERS
SET DEFINE OFF;
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID130','Ady','Admin Gudang','Brunei','82345654322','ady@gmail.com','60fe74406e7f353ed979f350f2fbb6a2e8690a5fa7d1b0c32983d1d8b3f95f67','UID129','0','STR123',to_date('17-12-2024','DD-MM-RRRR'),'1',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID122','Aqsa Zamzami','Owner','PNJ','81234567890','aqsa@gmail.com','4963df71690d18b8b13e47fcf1985723cc4896581faa1a959d58d7b6c0efd1a0',null,'0',null,to_date('05-12-2024','DD-MM-RRRR'),'0',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID126','Rifat','Admin Gudang','Gunung Putri','82162172334','rifatsyahman@gmail.com','60fe74406e7f353ed979f350f2fbb6a2e8690a5fa7d1b0c32983d1d8b3f95f67','UID119','0','STR112',to_date('09-12-2024','DD-MM-RRRR'),'1',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID121','Jotaro','Owner','Mangga Dua','89743653377','jojo@gmail.com','d9e1ae652ee896e3861d7ee8d95911f7012864247737e585a8985d9c2b6e61fd',null,'0',null,to_date('05-12-2024','DD-MM-RRRR'),'0',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID125','Angel','Admin Kasir','Kukusan','81238475929','angela@gmail.com','60fe74406e7f353ed979f350f2fbb6a2e8690a5fa7d1b0c32983d1d8b3f95f67','UID119','0','STR112',to_date('06-12-2024','DD-MM-RRRR'),'0',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID120','Dimas','Admin Gudang','Kalibata City','82233446699','dimas@gmail.com','60fe74406e7f353ed979f350f2fbb6a2e8690a5fa7d1b0c32983d1d8b3f95f67','UID119','0',null,to_date('05-12-2024','DD-MM-RRRR'),'0',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID127','Shazam','Owner','Depok, Jawa Barat','82124793703','aqsa.zamzami.tik23@stu.pnj.ac.id','513d88c03a6ac97253bbb9c7f86ed232b43541727fa5ea5840f2f9927221e26e',null,'0',null,to_date('10-12-2024','DD-MM-RRRR'),'0','be54e830fef0b9c26ac8e8f91a8ed207',null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID128','GECOF','Owner','PNJ DEPOK','8128123942','gecof.pnj@gmail.com','b2975ebf90bb6268f1c9f6b7e9acd9adcf9f67e6dbabbe6f79c131145d7db2de',null,'0',null,to_date('10-12-2024','DD-MM-RRRR'),'1',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID123','Rifat','Owner','Gunung Putri','88877665544','ripat@gmail.com','60fe74406e7f353ed979f350f2fbb6a2e8690a5fa7d1b0c32983d1d8b3f95f67',null,'0',null,to_date('06-12-2024','DD-MM-RRRR'),'0',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID124','AQSA ZAMZAMI','Admin Gudang','Komplek Kejaksaan Agung Blok F No. 11','82122050408','zamaqsa99@gmail.com','4963df71690d18b8b13e47fcf1985723cc4896581faa1a959d58d7b6c0efd1a0','UID123','0',null,to_date('06-12-2024','DD-MM-RRRR'),'0',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID129','Aqsa Zamzami','Owner','Pasar Minggu','82124050408','aqsazamzami099@gmail.com','60fe74406e7f353ed979f350f2fbb6a2e8690a5fa7d1b0c32983d1d8b3f95f67',null,'0','STR123',to_date('15-12-2024','DD-MM-RRRR'),'1',null,null);
Insert into C##INVENSYNC.I_USERS (USER_ID,NAME,ROLE,ADDRESS,PHONE_NUMBER,EMAIL,PASSWORD,OWNER_ID,IS_DELETED,STORE_ID,DATE_ADDED,IS_EMAIL_VERIFIED,VERIFICATION_TOKEN,CODE) values ('UID119','AQSA ZAMZAMI','Owner','Komplek Kejaksaan Agung Blok F No. 11','82122050408','aqsazamzami@gmail.com','4963df71690d18b8b13e47fcf1985723cc4896581faa1a959d58d7b6c0efd1a0',null,'0',null,to_date('05-12-2024','DD-MM-RRRR'),'1',null,null);
REM INSERTING into C##INVENSYNC.I_RECEIPT_ITEM
SET DEFINE OFF;
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT103','1','249000','RCP101','ITM102','0','STR112',to_timestamp('08-12-2024 01.27.31,727000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT114','2','215000','RCP107','ITM104','0','STR112',to_timestamp('14-12-2024 15.58.18,680000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT118','6','356900','RCP108','ITM106','0','STR112',to_timestamp('14-11-2024 19.41.41,111000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT120','1','356900','RCP111','ITM106','1','STR112',to_timestamp('17-12-2024 16.22.34,007000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT101','5','215000','RCP101','ITM104','0','STR112',to_timestamp('08-12-2024 01.26.08,378000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT102','1','215000','RCP101','ITM104','0','STR112',to_timestamp('08-12-2024 01.27.17,023000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT113','1','192000','RCP107','ITM101','1','STR112',to_timestamp('14-12-2024 15.58.12,376000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT104','13','192000','RCP102','ITM101','0','STR112',to_timestamp('10-12-2024 23.24.42,031000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT105','1','356900','RCP103','ITM106','0','STR112',to_timestamp('11-12-2024 12.30.17,812000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT106','1','215000','RCP103','ITM104','0','STR112',to_timestamp('11-12-2024 12.30.23,753000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT107','1','249000','RCP103','ITM102','0','STR112',to_timestamp('11-12-2024 12.30.28,211000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT108','1','192000','RCP103','ITM101','0','STR112',to_timestamp('11-12-2024 12.30.33,970000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT109','3','215000','RCP104','ITM104','0','STR112',to_timestamp('11-12-2024 12.31.05,152000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT110','2','356900','RCP104','ITM106','0','STR112',to_timestamp('11-12-2024 12.31.09,459000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT111','1','215000','RCP105','ITM104','0','STR112',to_timestamp('11-12-2024 13.52.48,026000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT112','11','249000','RCP106','ITM102','0','STR112',to_timestamp('12-12-2024 12.09.58,764000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT115','1','192000','RCP108','ITM101','1','STR112',to_timestamp('14-12-2024 15.59.05,095000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT116','2','215000','RCP108','ITM104','1','STR112',to_timestamp('14-12-2024 15.59.06,875000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT117','3','356900','RCP108','ITM106','1','STR112',to_timestamp('14-12-2024 15.59.09,680000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##INVENSYNC.I_RECEIPT_ITEM (RECEIPT_ITEM_ID,QUANTITY,TOTAL_PER_ITEM,RECEIPT_ID,ITEM_ID,IS_DELETED,STORE_ID,TIME_ADDED) values ('RIT119','-1','192000','RCP110','ITM101','0','STR112',to_timestamp('17-12-2024 13.28.05,757000000','DD-MM-RRRR HH24.MI.SSXFF'));
REM INSERTING into C##INVENSYNC.I_MASTER_ITEM
SET DEFINE OFF;
Insert into C##INVENSYNC.I_MASTER_ITEM (ITEM_ID,ITEM_NAME,COST_PRICE,CATEGORY_ID,IS_DELETED,BRAND_ID,STORE_ID,DATE_ADDED) values ('ITM101','Topi NYC 2K20','192000','CTG101','0','BRN101','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_ITEM (ITEM_ID,ITEM_NAME,COST_PRICE,CATEGORY_ID,IS_DELETED,BRAND_ID,STORE_ID,DATE_ADDED) values ('ITM104','Kemeja Flanel Biru','215000','CTG104','0','BRN105','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_ITEM (ITEM_ID,ITEM_NAME,COST_PRICE,CATEGORY_ID,IS_DELETED,BRAND_ID,STORE_ID,DATE_ADDED) values ('ITM105','Tas Ransel 25L Hitam','325900','CTG105','0','BRN107','STR119',to_date('10-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_ITEM (ITEM_ID,ITEM_NAME,COST_PRICE,CATEGORY_ID,IS_DELETED,BRAND_ID,STORE_ID,DATE_ADDED) values ('ITM106','Tas Gunung 40L Biru','356900','CTG106','0','BRN108','STR112',to_date('11-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_ITEM (ITEM_ID,ITEM_NAME,COST_PRICE,CATEGORY_ID,IS_DELETED,BRAND_ID,STORE_ID,DATE_ADDED) values ('ITM102','Jeans Robek-Robek','249000','CTG102','0','BRN103','STR112',to_date('06-12-2024','DD-MM-RRRR'));
Insert into C##INVENSYNC.I_MASTER_ITEM (ITEM_ID,ITEM_NAME,COST_PRICE,CATEGORY_ID,IS_DELETED,BRAND_ID,STORE_ID,DATE_ADDED) values ('ITM103','Kemeja Kotak Kotak Biru','129000','CTG103','0','BRN104','STR120',to_date('06-12-2024','DD-MM-RRRR'));
--------------------------------------------------------
--  DDL for Index PK_INVENTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."PK_INVENTORY" ON "C##INVENSYNC"."I_INVENTORY" ("INVENTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009418
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009418" ON "C##INVENSYNC"."I_RECEIPT" ("RECEIPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009489
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009489" ON "C##INVENSYNC"."I_MASTER_BRAND" ("BRAND_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009491
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009491" ON "C##INVENSYNC"."I_MASTER_CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009426
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009426" ON "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009411
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009411" ON "C##INVENSYNC"."I_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009422
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009422" ON "C##INVENSYNC"."I_RECEIPT_ITEM" ("RECEIPT_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C009438
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##INVENSYNC"."SYS_C009438" ON "C##INVENSYNC"."I_MASTER_ITEM" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ID" 
BEFORE INSERT ON I_RECEIPT
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ID := 'RCP' || RECEIPT_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_CATEGORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_CATEGORY_ID" 
BEFORE INSERT ON I_MASTER_CATEGORY
FOR EACH ROW
BEGIN
    :NEW.CATEGORY_ID := 'CTG' || MASTER_CATEGORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_CATEGORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ITEM_ID" 
BEFORE INSERT ON I_RECEIPT_ITEM
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ITEM_ID := 'RIT' || RECEIPT_ITEM_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STORE_INFO_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_STORE_INFO_ID" 
BEFORE INSERT ON I_STORE_INFO
FOR EACH ROW
BEGIN
    :NEW.STORE_ID := 'STR' || STORE_INFO_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_STORE_INFO_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_USERS_ID" 
BEFORE INSERT ON I_USERS
FOR EACH ROW
BEGIN
    :NEW.USER_ID := 'UID' || USERS_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_USERS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INVENTORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_INVENTORY_ID" 
BEFORE INSERT ON I_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.INVENTORY_ID := 'INV' || INVENTORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_INVENTORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_ITEM_ID" 
BEFORE INSERT ON I_MASTER_ITEM
FOR EACH ROW
BEGIN
    :NEW.ITEM_ID := 'ITM' || MASTER_ITEM_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_BRAND_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_BRAND_ID" 
BEFORE INSERT ON I_MASTER_BRAND
FOR EACH ROW
BEGIN
    :NEW.BRAND_ID := 'BRN' || MASTER_BRAND_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_BRAND_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INVENTORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_INVENTORY_ID" 
BEFORE INSERT ON I_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.INVENTORY_ID := 'INV' || INVENTORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_INVENTORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ID" 
BEFORE INSERT ON I_RECEIPT
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ID := 'RCP' || RECEIPT_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_BRAND_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_BRAND_ID" 
BEFORE INSERT ON I_MASTER_BRAND
FOR EACH ROW
BEGIN
    :NEW.BRAND_ID := 'BRN' || MASTER_BRAND_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_BRAND_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_CATEGORY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_CATEGORY_ID" 
BEFORE INSERT ON I_MASTER_CATEGORY
FOR EACH ROW
BEGIN
    :NEW.CATEGORY_ID := 'CTG' || MASTER_CATEGORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_CATEGORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STORE_INFO_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_STORE_INFO_ID" 
BEFORE INSERT ON I_STORE_INFO
FOR EACH ROW
BEGIN
    :NEW.STORE_ID := 'STR' || STORE_INFO_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_STORE_INFO_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_USERS_ID" 
BEFORE INSERT ON I_USERS
FOR EACH ROW
BEGIN
    :NEW.USER_ID := 'UID' || USERS_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_USERS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ITEM_ID" 
BEFORE INSERT ON I_RECEIPT_ITEM
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ITEM_ID := 'RIT' || RECEIPT_ITEM_SEQ.NEXTVAL;
END;

/
ALTER TRIGGER "C##INVENSYNC"."TRG_RECEIPT_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_MASTER_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##INVENSYNC"."TRG_MASTER_ITEM_ID" 
BEFORE INSERT ON I_MASTER_ITEM
FOR EACH ROW
BEGIN
    :NEW.ITEM_ID := 'ITM' || MASTER_ITEM_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "C##INVENSYNC"."TRG_MASTER_ITEM_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table I_INVENTORY
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" ADD CONSTRAINT "PK_INVENTORY" PRIMARY KEY ("INVENTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_RECEIPT
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_RECEIPT" ADD PRIMARY KEY ("RECEIPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_MASTER_BRAND
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_BRAND" MODIFY ("BRAND_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_MASTER_BRAND" ADD PRIMARY KEY ("BRAND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_MASTER_CATEGORY
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_STORE_INFO
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_STORE_INFO" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_STORE_INFO" ADD PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_USERS
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_USERS" MODIFY ("IS_DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table I_RECEIPT_ITEM
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" MODIFY ("TOTAL_PER_ITEM" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" ADD PRIMARY KEY ("RECEIPT_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" MODIFY ("IS_DELETED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table I_MASTER_ITEM
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" MODIFY ("COST_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_INVENTORY
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "C##INVENSYNC"."I_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" ADD CONSTRAINT "FK_INVENTORY_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "C##INVENSYNC"."I_MASTER_ITEM" ("ITEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_INVENTORY" ADD CONSTRAINT "FK_STORE_INVENTORY" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_RECEIPT
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_RECEIPT" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "C##INVENSYNC"."I_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT" ADD CONSTRAINT "FK_STORE_RECEIPT" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_MASTER_BRAND
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_BRAND" ADD CONSTRAINT "FK_STORE_BRAND" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_MASTER_CATEGORY
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_CATEGORY" ADD CONSTRAINT "FK_STORE_CATEGORY" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_STORE_INFO
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_STORE_INFO" ADD CONSTRAINT "FK_OWNERSTORE" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "C##INVENSYNC"."I_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_USERS
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_USERS" ADD CONSTRAINT "FK_OWNERID" FOREIGN KEY ("OWNER_ID")
	  REFERENCES "C##INVENSYNC"."I_USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_USERS" ADD CONSTRAINT "FK_STORE_USERS" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_RECEIPT_ITEM
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" ADD FOREIGN KEY ("RECEIPT_ID")
	  REFERENCES "C##INVENSYNC"."I_RECEIPT" ("RECEIPT_ID") ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" ADD CONSTRAINT "FK_RECEIPT_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "C##INVENSYNC"."I_MASTER_ITEM" ("ITEM_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_RECEIPT_ITEM" ADD CONSTRAINT "FK_RECEIPT_ITEM_USERS" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_MASTER_ITEM
--------------------------------------------------------

  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" ADD CONSTRAINT "FK_BRAND_ITEM" FOREIGN KEY ("BRAND_ID")
	  REFERENCES "C##INVENSYNC"."I_MASTER_BRAND" ("BRAND_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" ADD CONSTRAINT "FK_CATEGORY_ITEM" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "C##INVENSYNC"."I_MASTER_CATEGORY" ("CATEGORY_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##INVENSYNC"."I_MASTER_ITEM" ADD CONSTRAINT "FK_STORE_ITEM" FOREIGN KEY ("STORE_ID")
	  REFERENCES "C##INVENSYNC"."I_STORE_INFO" ("STORE_ID") ON DELETE CASCADE ENABLE;
