--------------------------------------------------------
--  File created - Sunday-November-10-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAHASISWA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MAHASISWA" 
   (	"NIM" VARCHAR2(15 BYTE), 
	"FULL_NAME" VARCHAR2(100 BYTE), 
	"JURUSAN" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_DAMAGED_ITEM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_DAMAGED_ITEM" 
   (	"DAMAGED_ID" VARCHAR2(15 BYTE), 
	"DATE_DAMAGED" DATE DEFAULT SYSDATE, 
	"DAMAGED_DESC" VARCHAR2(255 BYTE), 
	"QTY_DAMAGED" NUMBER, 
	"ACTION" VARCHAR2(100 BYTE), 
	"COST" NUMBER(10,2), 
	"ITEM_ID" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_INVENTORY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_INVENTORY" 
   (	"ITEM_ID" VARCHAR2(15 BYTE), 
	"ITEM_NAME" VARCHAR2(100 BYTE), 
	"QUANTITY" NUMBER DEFAULT 0, 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"HARGA_BELI" NUMBER(10,2), 
	"HARGA_JUAL" NUMBER(10,2), 
	"STATUS" VARCHAR2(50 BYTE), 
	"DATE_EXPIRED" DATE, 
	"USER_ID" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_RECEIPT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_RECEIPT" 
   (	"RECEIPT_ID" VARCHAR2(15 BYTE), 
	"DATE_ADDED" DATE DEFAULT SYSDATE, 
	"TOTAL_PRICE" NUMBER(10,2), 
	"USER_ID" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_RECEIPT_ITEM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_RECEIPT_ITEM" 
   (	"RECEIPT_ITEM_ID" VARCHAR2(15 BYTE), 
	"QUANTITY" NUMBER, 
	"TOTAL_PER_ITEM" NUMBER(10,2), 
	"RECEIPT_ID" VARCHAR2(15 BYTE), 
	"ITEM_ID" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_STORE_INFO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_STORE_INFO" 
   (	"STORE_ID" VARCHAR2(15 BYTE), 
	"STORE_NAME" VARCHAR2(100 BYTE), 
	"STORE_TYPE" VARCHAR2(50 BYTE), 
	"LOCATION" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"YEAR_FOUNDED" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table I_USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."I_USERS" 
   (	"USER_ID" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(150 BYTE), 
	"PHONE_NUMBER" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"STORE_ID" VARCHAR2(15 BYTE), 
	"USERNAME" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MAHASISWA
SET DEFINE OFF;
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411053','AMIR HAMZAH','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411041','ACHMAD ZIKRAN MAULIDA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411052','RIDHO SYAHTRA PRATAMA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411030','MUHAMMAD','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411048','AQSA ZAMZAMI','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411040','MUHAMMAD DZAKY FAUZAN','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411039','MUHAMAD RAFI ABDURACHMAN PUTRA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411047','ACHMAD DHANI SYAHPUTRA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411062','RAMADHAN NAUFAL RAHMANTIO','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411044','MARVIN RADITYA NUGRAHA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411031','MOCHAMAD RIFAT SYAHMAN HAMBALI','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411051','AHMAD MUKHLASH MUHTADY','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411056','RIZKI MAULANA LESMANA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411042','YASMEEN ALMIRA','TEKNIK INFORMATIKA DAN KOMPUTER','PEREMPUAN');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411038','MUHTRIA HARLIKA','TEKNIK INFORMATIKA DAN KOMPUTER','PEREMPUAN');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411058','VIRGINIA ANGEL ALEXANDRA SOEN','TEKNIK INFORMATIKA DAN KOMPUTER','PEREMPUAN');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411050','NAJMA GUSTI AYU MAHESA','TEKNIK INFORMATIKA DAN KOMPUTER','PEREMPUAN');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411061','MELVIN OKNIEL SINAGA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411057','MUHAMAD GERRALDY GHASSAN HERFIO','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411037','NAESYA QONITHA','TEKNIK INFORMATIKA DAN KOMPUTER','PEREMPUAN');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411060','FARREL JAZIRAH RAMADHAN','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411049','MUHAMMAD SYUKRON RIZKY FADILLA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411036','MUHAMMAD ARYA MAULANA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411034','JOSE FEBRIAN LIMBOR','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411043','REYNALDI CHANDRA KIRANA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411033','SULTHAN ISLAMI ZACKY','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411059','MUHAMMAD HAFIZ','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411032','XEYLA VITHRA ARFHINA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307411035','VIRGIO MAHARDIKA DANANG PUTRA','TEKNIK INFORMATIKA DAN KOMPUTER','LAKI-LAKI');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2304044029','zyassar alfalfa bafano','Sastra Mesin','Laki-laki');
Insert into SYSTEM.MAHASISWA (NIM,FULL_NAME,JURUSAN,GENDER) values ('2307416969','XEYYYY','TEKNIK KEDOKTERAN','LAKI-LAKI');
REM INSERTING into SYSTEM.I_DAMAGED_ITEM
SET DEFINE OFF;
REM INSERTING into SYSTEM.I_INVENTORY
SET DEFINE OFF;
REM INSERTING into SYSTEM.I_RECEIPT
SET DEFINE OFF;
REM INSERTING into SYSTEM.I_RECEIPT_ITEM
SET DEFINE OFF;
REM INSERTING into SYSTEM.I_STORE_INFO
SET DEFINE OFF;
REM INSERTING into SYSTEM.I_USERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C009309
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009309" ON "SYSTEM"."MAHASISWA" ("NIM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009384
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009384" ON "SYSTEM"."I_DAMAGED_ITEM" ("DAMAGED_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009375
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009375" ON "SYSTEM"."I_INVENTORY" ("ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009377
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009377" ON "SYSTEM"."I_RECEIPT" ("RECEIPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009381
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009381" ON "SYSTEM"."I_RECEIPT_ITEM" ("RECEIPT_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009365
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009365" ON "SYSTEM"."I_STORE_INFO" ("STORE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009366
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009366" ON "SYSTEM"."I_STORE_INFO" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009367
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009367" ON "SYSTEM"."I_STORE_INFO" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009370
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009370" ON "SYSTEM"."I_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009371
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009371" ON "SYSTEM"."I_USERS" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C009372
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009372" ON "SYSTEM"."I_USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_DAMAGED_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_DAMAGED_ITEM_ID" 
BEFORE INSERT ON I_DAMAGED_ITEM
FOR EACH ROW
BEGIN
    :NEW.DAMAGED_ID := 'DMG' || DAMAGED_ITEM_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_DAMAGED_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_INVENTORY_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_INVENTORY_ID" 
BEFORE INSERT ON I_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.ITEM_ID := 'ITM' || INVENTORY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_INVENTORY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_RECEIPT_ID" 
BEFORE INSERT ON I_RECEIPT
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ID := 'RCP' || RECEIPT_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_RECEIPT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_RECEIPT_ITEM_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_RECEIPT_ITEM_ID" 
BEFORE INSERT ON I_RECEIPT_ITEM
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ITEM_ID := 'RIT' || RECEIPT_ITEM_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_RECEIPT_ITEM_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_STORE_INFO_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_STORE_INFO_ID" 
BEFORE INSERT ON I_STORE_INFO
FOR EACH ROW
BEGIN
    :NEW.STORE_ID := 'STR' || STORE_INFO_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SYSTEM"."TRG_STORE_INFO_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_USERS_ID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."TRG_USERS_ID" 
BEFORE INSERT ON I_USERS
FOR EACH ROW
BEGIN
    :NEW.USER_ID := 'USR' || USERS_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_store_info_id
BEFORE INSERT ON I_STORE_INFO
FOR EACH ROW
BEGIN
    :NEW.STORE_ID := 'STR' || STORE_INFO_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_inventory_id
BEFORE INSERT ON I_INVENTORY
FOR EACH ROW
BEGIN
    :NEW.ITEM_ID := 'ITM' || INVENTORY_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_receipt_id
BEFORE INSERT ON I_RECEIPT
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ID := 'RCP' || RECEIPT_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_receipt_item_id
BEFORE INSERT ON I_RECEIPT_ITEM
FOR EACH ROW
BEGIN
    :NEW.RECEIPT_ITEM_ID := 'RIT' || RECEIPT_ITEM_SEQ.NEXTVAL;
END;


CREATE OR REPLACE TRIGGER trg_damaged_item_id
BEFORE INSERT ON I_DAMAGED_ITEM
FOR EACH ROW
BEGIN
    :NEW.DAMAGED_ID := 'DMG' || DAMAGED_ITEM_SEQ.NEXTVAL;
END;

ALTER TABLE users
ADD username VARCHAR2(100);
/
ALTER TRIGGER "SYSTEM"."TRG_USERS_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table MAHASISWA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MAHASISWA" MODIFY ("FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MAHASISWA" MODIFY ("JURUSAN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MAHASISWA" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MAHASISWA" ADD PRIMARY KEY ("NIM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_DAMAGED_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_DAMAGED_ITEM" ADD PRIMARY KEY ("DAMAGED_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_INVENTORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_INVENTORY" MODIFY ("ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_INVENTORY" ADD PRIMARY KEY ("ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_RECEIPT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_RECEIPT" ADD PRIMARY KEY ("RECEIPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_RECEIPT_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" MODIFY ("TOTAL_PER_ITEM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" ADD PRIMARY KEY ("RECEIPT_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_STORE_INFO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_STORE_INFO" MODIFY ("STORE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_STORE_INFO" ADD PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."I_STORE_INFO" ADD UNIQUE ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."I_STORE_INFO" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table I_USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."I_USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."I_USERS" ADD UNIQUE ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."I_USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_DAMAGED_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_DAMAGED_ITEM" ADD FOREIGN KEY ("ITEM_ID")
	  REFERENCES "SYSTEM"."I_INVENTORY" ("ITEM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_INVENTORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_INVENTORY" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."I_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_RECEIPT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_RECEIPT" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM"."I_USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_RECEIPT_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" ADD FOREIGN KEY ("RECEIPT_ID")
	  REFERENCES "SYSTEM"."I_RECEIPT" ("RECEIPT_ID") ENABLE;
  ALTER TABLE "SYSTEM"."I_RECEIPT_ITEM" ADD FOREIGN KEY ("ITEM_ID")
	  REFERENCES "SYSTEM"."I_INVENTORY" ("ITEM_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table I_USERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."I_USERS" ADD FOREIGN KEY ("STORE_ID")
	  REFERENCES "SYSTEM"."I_STORE_INFO" ("STORE_ID") ENABLE;
